// Package golden runs the differential test corpus against the reference
// outputs produced by the original Rust implementation.
//
// The corpus (testdata/corpus.jsonl) and the reference results
// (testdata/goldens/rust.jsonl) are generated by tools/refgen, a small Rust
// binary built against the original crates. Every case is replayed through the
// Go implementation and the JSON output must match byte for byte, apart from
// volatile timestamps which are normalised to zero.
package golden

import (
	"context"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/dandandujie/dsr-go/core"
	"github.com/dandandujie/dsr-go/core/jsonx"
	"github.com/dandandujie/dsr-go/encoding"
	"github.com/dandandujie/dsr-go/encoding/tokenizer"
	"github.com/dandandujie/dsr-go/encoding/v4/dsv4"
	"github.com/dandandujie/dsr-go/encoding/v4/dsv41"
	"github.com/dandandujie/dsr-go/image"
	"github.com/dandandujie/dsr-go/recipe/anthropic/messages"
	"github.com/dandandujie/dsr-go/recipe/openai/chatcompletion"
	"github.com/dandandujie/dsr-go/recipe/openai/responses"
	"github.com/dandandujie/dsr-go/recipe/request"
	"github.com/dandandujie/dsr-go/recipe/response"
	"github.com/dandandujie/dsr-go/recipe/stream"
)

// corpusCase is one differential test case.
type corpusCase struct {
	Name        string            `json:"name"`
	Op          string            `json:"op"`
	Protocol    string            `json:"protocol"`
	Body        json.RawMessage   `json:"body"`
	Chunks      []json.RawMessage `json:"chunks"`
	Tokenizer   string            `json:"tokenizer"`
	Value       json.RawMessage   `json:"value"`
	Text        string            `json:"text"`
	IDs         []uint32          `json:"ids"`
	Numbers     []string          `json:"numbers"`
	SkipSpecial bool              `json:"skip_special_tokens"`
	Encoding    string            `json:"encoding"`
	Sources     []imageSourceSpec `json:"sources"`
	// fuzz marks cases from the randomized corpus, where JSON type-mismatch
	// wording may differ between serde and encoding/json.
	fuzz bool
}

// chunkSpec mirrors the refgen chunk specification.
type chunkSpec struct {
	Kind                 string  `json:"kind"`
	SystemFingerprint    *string `json:"system_fingerprint"`
	PromptTokens         int     `json:"prompt_tokens"`
	PromptCacheHitTokens int     `json:"prompt_cache_hit_tokens"`
	Content              string  `json:"content"`
	ContentTokens        int     `json:"content_tokens"`
	TokenID              uint32  `json:"token_id"`
	Text                 string  `json:"text"`
	FinishReason         string  `json:"finish_reason"`
}

// adapter binds one protocol package to the harness without generics.
type adapter struct {
	name string
	// convert deserializes and converts a request body.
	convert func(body []byte) (*request.ConversationRequest, error)
	// newGenerator builds the protocol event generator.
	newGenerator func(req *request.ConversationRequest, id, model string) stream.Generator
	// newResponse builds an empty accumulator for the protocol.
	newResponse func(id, model string, created uint64) response.ProtocolResponse
	// ops lists the operations that need this adapter.
	ops map[string]bool
}

func newChatCompletionsAdapter() *adapter {
	return &adapter{
		name: "chat_completions",
		convert: func(body []byte) (*request.ConversationRequest, error) {
			var typed chatcompletion.ChatCompletionRequest
			if err := json.Unmarshal(body, &typed); err != nil {
				return nil, request.BadRequestf("invalid request body: %v", err)
			}
			return typed.Convert(request.NewConversionOptions())
		},
		newGenerator: func(req *request.ConversationRequest, id, model string) stream.Generator {
			return req.NewChunkGenerator(id, model)
		},
		newResponse: func(id, model string, created uint64) response.ProtocolResponse {
			return chatcompletion.NewChatCompletionResponse(id, model, created)
		},
		ops: map[string]bool{"convert": true, "render": true, "encode": true, "stream": true, "complete": true},
	}
}

func newMessagesAdapter() *adapter {
	return &adapter{
		name: "messages",
		convert: func(body []byte) (*request.ConversationRequest, error) {
			var typed messages.MessagesRequest
			if err := json.Unmarshal(body, &typed); err != nil {
				return nil, request.BadRequestf("invalid request body: %v", err)
			}
			return typed.Convert(request.NewConversionOptions())
		},
		newGenerator: func(req *request.ConversationRequest, id, model string) stream.Generator {
			return req.NewChunkGenerator(id, model)
		},
		newResponse: func(id, model string, created uint64) response.ProtocolResponse {
			return messages.NewMessagesResponse(id, model, created)
		},
		ops: map[string]bool{"convert": true, "render": true, "encode": true, "stream": true, "complete": true},
	}
}

func newResponsesAdapter() *adapter {
	return &adapter{
		name: "responses",
		convert: func(body []byte) (*request.ConversationRequest, error) {
			var typed responses.ResponsesRequest
			if err := json.Unmarshal(body, &typed); err != nil {
				return nil, request.BadRequestf("invalid request body: %v", err)
			}
			return typed.Convert(request.NewConversionOptions())
		},
		newGenerator: func(req *request.ConversationRequest, id, model string) stream.Generator {
			return req.NewChunkGenerator(id, model)
		},
		newResponse: func(id, model string, created uint64) response.ProtocolResponse {
			return responses.NewResponsesResponse(id, model, created)
		},
		ops: map[string]bool{"convert": true, "render": true, "encode": true, "stream": true, "complete": true},
	}
}

func adapters() map[string]*adapter {
	list := []*adapter{newChatCompletionsAdapter(), newResponsesAdapter(), newMessagesAdapter()}
	out := make(map[string]*adapter, len(list))
	for _, item := range list {
		out[item.name] = item
	}
	return out
}

var (
	createdPattern = regexp.MustCompile(`"(created|created_at|completed_at)":\d+`)

	tokenizerMu    sync.Mutex
	tokenizerCache = map[string]*tokenizer.Tokenizer{}
)

func normalizeVolatile(text string) string {
	return createdPattern.ReplaceAllString(text, `"$1":0`)
}

// loadTokenizer loads a bundled tokenizer by directory name ("v4" or "v41").
func loadTokenizer(name string) (*tokenizer.Tokenizer, error) {
	if name == "" {
		name = "v41"
	}
	tokenizerMu.Lock()
	defer tokenizerMu.Unlock()
	if cached, ok := tokenizerCache[name]; ok {
		return cached, nil
	}
	path := filepath.Join("..", "static", "tokenizers", name, "tokenizer.json")
	loaded, err := tokenizer.Load(path)
	if err != nil {
		return nil, err
	}
	tokenizerCache[name] = loaded
	return loaded, nil
}

// corpusFiles returns the committed corpus/golden pairs, plus an ad-hoc pair
// from DSR_EXTRA_CORPUS and DSR_EXTRA_GOLDEN when set.
func corpusFiles() [][2]string {
	pairs := [][2]string{{"corpus.jsonl", filepath.Join("goldens", "rust.jsonl")}}
	if _, err := os.Stat(filepath.Join("..", "testdata", "corpus_fuzz.jsonl")); err == nil {
		pairs = append(pairs, [2]string{"corpus_fuzz.jsonl", filepath.Join("goldens", "rust_fuzz.jsonl")})
	}
	if extra := os.Getenv("DSR_EXTRA_CORPUS"); extra != "" {
		pairs = append(pairs, [2]string{extra, os.Getenv("DSR_EXTRA_GOLDEN")})
	}
	return pairs
}

func loadCorpus(tb testing.TB) ([]corpusCase, map[string]string) {
	tb.Helper()
	root := filepath.Join("..", "testdata")
	var cases []corpusCase
	goldens := make(map[string]string)
	for index, pair := range corpusFiles() {
		corpusPath := filepath.Join(root, pair[0])
		goldenPath := filepath.Join(root, pair[1])
		if filepath.IsAbs(pair[0]) {
			corpusPath = pair[0]
		}
		if filepath.IsAbs(pair[1]) {
			goldenPath = pair[1]
		}
		corpusData, err := os.ReadFile(corpusPath)
		if err != nil {
			tb.Fatalf("read corpus %s: %v", pair[0], err)
		}
		goldenData, err := os.ReadFile(goldenPath)
		if err != nil {
			tb.Fatalf("read goldens %s: %v", pair[1], err)
		}
		isFuzz := index > 0
		for _, line := range strings.Split(strings.TrimSpace(string(corpusData)), "\n") {
			if strings.TrimSpace(line) == "" {
				continue
			}
			var item corpusCase
			if err := json.Unmarshal([]byte(line), &item); err != nil {
				tb.Fatalf("parse corpus line: %v", err)
			}
			item.fuzz = isFuzz
			cases = append(cases, item)
		}
		for _, line := range strings.Split(strings.TrimSpace(string(goldenData)), "\n") {
			if strings.TrimSpace(line) == "" {
				continue
			}
			var item struct {
				Name string `json:"name"`
			}
			if err := json.Unmarshal([]byte(line), &item); err != nil {
				tb.Fatalf("parse golden line: %v", err)
			}
			goldens[item.Name] = line
		}
	}
	return cases, goldens
}

// sameErrorKind reports whether two results are both failures with the same
// error kind, differing only in the human-readable detail.
func sameErrorKind(want, got string) bool {
	var wantValue, gotValue struct {
		OK    bool `json:"ok"`
		Error struct {
			Kind string `json:"kind"`
		} `json:"error"`
	}
	if err := json.Unmarshal([]byte(want), &wantValue); err != nil {
		return false
	}
	if err := json.Unmarshal([]byte(got), &gotValue); err != nil {
		return false
	}
	return !wantValue.OK && !gotValue.OK && wantValue.Error.Kind == gotValue.Error.Kind
}

func TestGoldenCorpus(t *testing.T) {
	cases, goldens := loadCorpus(t)
	registry := adapters()
	tested, skipped := 0, 0
	for _, item := range cases {
		item := item
		t.Run(item.Name, func(t *testing.T) {
			got, err := runCase(item, registry)
			if err != nil {
				t.Fatalf("run: %v", err)
			}
			if got == nil {
				skipped++
				t.Skip("operation not supported yet")
			}
			want, ok := goldens[item.Name]
			if !ok {
				t.Fatalf("no reference result for %s", item.Name)
			}
			tested++
			wantText := normalizeVolatile(want)
			gotText := normalizeVolatile(*got)
			if wantText != gotText {
				if item.fuzz && sameErrorKind(wantText, gotText) {
					t.Logf("error detail wording differs (kind matches)\nwant: %s\n got: %s", wantText, gotText)
					return
				}
				t.Errorf("reference mismatch\nwant: %s\n got: %s", wantText, gotText)
			}
		})
	}
	t.Logf("golden cases run: %d, skipped: %d", tested, skipped)
}

// runCase replays one corpus case and returns the JSON result, or nil when the
// operation is not implemented.
func runCase(item corpusCase, registry map[string]*adapter) (*string, error) {
	switch item.Op {
	case "image":
		return runImageCase(item)
	case "stringify":
		value, err := jsonx.Parse(item.Value)
		if err != nil {
			return nil, err
		}
		text, err := jsonx.MarshalPython(value)
		if err != nil {
			return nil, err
		}
		result := jsonx.NewObject()
		result.Set("text", text)
		return encodeResult(item.Name, result), nil
	case "numbers":
		compact := make(jsonx.Array, 0, len(item.Numbers))
		python := make(jsonx.Array, 0, len(item.Numbers))
		for _, number := range item.Numbers {
			value, err := jsonx.ParseString(number)
			if err != nil {
				return nil, err
			}
			compactText, err := jsonx.Marshal(value)
			if err != nil {
				return nil, err
			}
			pythonText, err := jsonx.MarshalPython(value)
			if err != nil {
				return nil, err
			}
			compact = append(compact, string(compactText))
			python = append(python, pythonText)
		}
		result := jsonx.NewObject()
		result.Set("compact", compact)
		result.Set("python", python)
		return encodeResult(item.Name, result), nil
	case "tokenize":
		loaded, err := loadTokenizer(item.Tokenizer)
		if err != nil {
			return nil, err
		}
		ids, err := loaded.EncodeIDs(item.Text)
		if err != nil {
			return nil, err
		}
		array := make(jsonx.Array, 0, len(ids))
		for _, id := range ids {
			array = append(array, int64(id))
		}
		result := jsonx.NewObject()
		result.Set("ids", array)
		return encodeResult(item.Name, result), nil
	case "detokenize":
		loaded, err := loadTokenizer(item.Tokenizer)
		if err != nil {
			return nil, err
		}
		text, err := loaded.DecodeIDs(item.IDs, item.SkipSpecial)
		if err != nil {
			return nil, err
		}
		result := jsonx.NewObject()
		result.Set("text", text)
		return encodeResult(item.Name, result), nil
	}

	impl, ok := registry[item.Protocol]
	if !ok || !impl.ops[item.Op] {
		return nil, nil
	}
	converted, err := impl.convert(item.Body)
	if err != nil {
		return encodeError(item.Name, err), nil
	}
	switch item.Op {
	case "convert":
		return encodeResult(item.Name, dumpConversion(converted)), nil
	case "render":
		var rendered encoding.RenderedPrompt
		if item.Encoding == "v4" {
			rendered = dsv4.New().RenderConversation(converted.Conversation)
		} else {
			rendered = dsv41.New().RenderConversation(converted.Conversation)
		}
		result := jsonx.NewObject()
		result.Set("prompt", rendered.Prompt)
		result.Set("image_sources", dumpImages(rendered.ImageSources))
		return encodeResult(item.Name, result), nil
	case "encode":
		loaded, err := loadTokenizer(item.Tokenizer)
		if err != nil {
			return nil, err
		}
		var ids []uint32
		if item.Encoding == "v4" {
			ids, err = dsv4.New().WithTokenizer(loaded).Encode(converted.Conversation)
		} else {
			ids, err = dsv41.New().WithTokenizer(loaded).Encode(converted.Conversation)
		}
		if err != nil {
			return encodeError(item.Name, err), nil
		}
		array := make(jsonx.Array, 0, len(ids))
		for _, id := range ids {
			array = append(array, int64(id))
		}
		result := jsonx.NewObject()
		result.Set("ids", array)
		return encodeResult(item.Name, result), nil
	case "stream":
		return runStream(item, impl, converted)
	case "complete":
		return runComplete(item, impl, converted)
	}
	return nil, fmt.Errorf("unknown op %q", item.Op)
}

// imageSourceSpec mirrors the reference generator image source specification.
type imageSourceSpec struct {
	Kind    string `json:"kind"`
	DataURL string `json:"data_url"`
	URL     string `json:"url"`
	Hex     string `json:"hex"`
	Detail  string `json:"detail"`
}

// imageStubFetcher mirrors the reference generator fetcher.
type imageStubFetcher struct{}

var (
	fetchSeenMu sync.Mutex
	fetchSeen   = map[string]bool{}
)

func (imageStubFetcher) Fetch(_ context.Context, url string, budget *image.ImageByteBudget) ([]byte, error) {
	if strings.Contains(url, "fail-always") {
		return nil, image.NewFetchError(url, errors.New("stub failure"))
	}
	if strings.Contains(url, "fail-once") {
		fetchSeenMu.Lock()
		first := !fetchSeen[url]
		fetchSeen[url] = true
		fetchSeenMu.Unlock()
		if first {
			return nil, image.NewFetchError(url, errors.New("stub transient failure"))
		}
	}
	data := []byte("bytes:" + url)
	if err := budget.Reserve(len(data)); err != nil {
		return nil, err
	}
	return data, nil
}

// imageStubPreprocessor mirrors the reference generator preprocessor.
type imageStubPreprocessor struct{}

func (imageStubPreprocessor) Preprocess(_ context.Context, data []byte, options image.PreprocessOptions) (core.ImageInfo, error) {
	length := len(data)
	out := make([]byte, 0, length+32)
	out = append(out, data...)
	out = append(out, []byte(fmt.Sprintf("|%s|%d|%d", options.Detail.String(), options.MaxDimensionPx, options.LowDetailMaxDimensionPx))...)
	return core.ImageInfo{Data: out, Width: uint32(length%97 + 1), Height: uint32(length/97 + 1)}, nil
}

// runImageCase resolves image sources with the same stubs as the reference
// generator and dumps the result.
func runImageCase(item corpusCase) (*string, error) {
	sources := make([]core.ImageSource, 0, len(item.Sources))
	for _, spec := range item.Sources {
		detail := core.ImageDetailHigh
		if parsed, ok := core.ParseImageDetail(spec.Detail); ok {
			detail = parsed
		}
		switch spec.Kind {
		case "data_url":
			sources = append(sources, core.DataURLImageSource(spec.DataURL, detail))
		case "url":
			sources = append(sources, core.URLImageSource(spec.URL, detail))
		case "bytes":
			data, err := hex.DecodeString(spec.Hex)
			if err != nil {
				return nil, err
			}
			sources = append(sources, core.BytesImageSource(data, detail))
		default:
			return nil, fmt.Errorf("unknown image source kind %q", spec.Kind)
		}
	}
	quota := image.NewImageQuota()
	resolver := image.NewImageResolver(imageStubFetcher{}, imageStubPreprocessor{}).
		WithRetry(image.NewRetryPolicy([]time.Duration{0, 0}))
	data, err := resolver.Resolve(sources, quota)
	if err != nil {
		return encodeError(item.Name, request.BadRequest(err.Error())), nil
	}
	images := make(jsonx.Array, 0, len(data.Images))
	for _, resolved := range data.Images {
		entry := jsonx.NewObject()
		entry.Set("width", int64(resolved.Width))
		entry.Set("height", int64(resolved.Height))
		entry.Set("data", hex.EncodeToString(resolved.Data))
		images = append(images, entry)
	}
	result := jsonx.NewObject()
	result.Set("images", images)
	result.Set("quota_images", int64(quota.ImageCount()))
	result.Set("quota_bytes", int64(quota.ByteSize()))
	return encodeResult(item.Name, result), nil
}

func runStream(item corpusCase, impl *adapter, converted *request.ConversationRequest) (*string, error) {
	specs, err := decodeChunks(item.Chunks)
	if err != nil {
		return nil, err
	}
	generator := impl.newGenerator(converted, "mock-id", "deepseek-flash")
	processor := stream.NewProcessor(generator, converted.ParsingOptions)
	inference, err := buildChunks(specs, item.Tokenizer)
	if err != nil {
		return encodeError(item.Name, request.BadRequest(err.Error())), nil
	}
	if needsTokenizer(specs) {
		loaded, err := loadTokenizer(item.Tokenizer)
		if err != nil {
			return nil, err
		}
		processor = processor.WithTokenizer(loaded)
	}
	events := make(jsonx.Array, 0, len(inference))
	for _, chunk := range inference {
		produced, err := processor.Push(chunk)
		if err != nil {
			return encodeError(item.Name, err), nil
		}
		for _, event := range produced {
			value, err := eventValue(event)
			if err != nil {
				return nil, err
			}
			events = append(events, value)
		}
	}
	for _, event := range processor.Finish() {
		value, err := eventValue(event)
		if err != nil {
			return nil, err
		}
		events = append(events, value)
	}
	result := jsonx.NewObject()
	result.Set("events", events)
	return encodeResult(item.Name, result), nil
}

func runComplete(item corpusCase, impl *adapter, converted *request.ConversationRequest) (*string, error) {
	specs, err := decodeChunks(item.Chunks)
	if err != nil {
		return nil, err
	}
	generator := impl.newGenerator(converted, "mock-id", "deepseek-flash")
	processor := stream.NewProcessor(generator, converted.ParsingOptions)
	inference, err := buildChunks(specs, item.Tokenizer)
	if err != nil {
		return encodeError(item.Name, request.BadRequest(err.Error())), nil
	}
	accumulator := impl.newResponse("mock-id", "deepseek-flash", 0)
	for _, chunk := range inference {
		produced, err := processor.Push(chunk)
		if err != nil {
			return encodeError(item.Name, err), nil
		}
		for _, event := range produced {
			accumulator.Append(event)
		}
	}
	for _, event := range processor.Finish() {
		accumulator.Append(event)
	}
	text, err := jsonx.MarshalCompactString(accumulator)
	if err != nil {
		return nil, err
	}
	value, err := jsonx.ParseString(text)
	if err != nil {
		return nil, err
	}
	return encodeResult(item.Name, value), nil
}

func needsTokenizer(specs []chunkSpec) bool {
	for _, spec := range specs {
		if spec.Kind == "token_text" {
			return true
		}
	}
	return false
}

func eventValue(event stream.Event) (jsonx.Value, error) {
	text, err := jsonx.MarshalCompactString(event)
	if err != nil {
		return nil, err
	}
	return jsonx.ParseString(text)
}

func decodeChunks(raw []json.RawMessage) ([]chunkSpec, error) {
	specs := make([]chunkSpec, 0, len(raw))
	for _, item := range raw {
		var spec chunkSpec
		if err := json.Unmarshal(item, &spec); err != nil {
			return nil, err
		}
		specs = append(specs, spec)
	}
	return specs, nil
}

func buildChunks(specs []chunkSpec, tokenizerName string) ([]stream.InferenceChunk, error) {
	chunks := make([]stream.InferenceChunk, 0, len(specs))
	for _, spec := range specs {
		switch spec.Kind {
		case "ready":
			chunks = append(chunks, stream.NewReadyChunk(spec.SystemFingerprint, stream.PromptUsage{
				PromptTokens:         spec.PromptTokens,
				PromptCacheHitTokens: spec.PromptCacheHitTokens,
			}))
		case "text":
			chunks = append(chunks, stream.NewTextChunk(spec.Content, spec.ContentTokens))
		case "token":
			chunks = append(chunks, stream.NewTokenChunk(spec.TokenID))
		case "token_text":
			if tokenizerName == "" {
				return nil, errTokenTextWithoutTokenizer
			}
			loaded, err := loadTokenizer(tokenizerName)
			if err != nil {
				return nil, err
			}
			ids, err := loaded.EncodeIDs(spec.Text)
			if err != nil {
				return nil, err
			}
			for _, id := range ids {
				chunks = append(chunks, stream.NewTokenChunk(id))
			}
		case "finish":
			reason := stream.InferenceFinishStop
			switch spec.FinishReason {
			case "length":
				reason = stream.InferenceFinishLength
			case "content_filter":
				reason = stream.InferenceFinishContentFilter
			}
			chunks = append(chunks, stream.NewFinishChunk(reason))
		default:
			return nil, fmt.Errorf("unknown chunk kind %q", spec.Kind)
		}
	}
	return chunks, nil
}

// errTokenTextWithoutTokenizer mirrors the reference generator, which refuses a
// token_text chunk when the case carries no tokenizer.
var errTokenTextWithoutTokenizer = errors.New("token_text chunk requires a tokenizer")

func encodeResult(name string, result jsonx.Value) *string {
	out := jsonx.NewObject()
	out.Set("ok", true)
	out.Set("result", result)
	out.Set("name", name)
	text, err := jsonx.Marshal(out)
	if err != nil {
		return nil
	}
	encoded := string(text)
	return &encoded
}

func encodeError(name string, err error) *string {
	kind := "internal"
	detail := err.Error()
	if conversion, ok := err.(*request.ConversionError); ok {
		detail = conversion.Detail
		if conversion.Kind == request.ConversionBadRequest {
			kind = "bad_request"
		}
	}
	errorObject := jsonx.NewObject()
	errorObject.Set("kind", kind)
	errorObject.Set("detail", detail)
	out := jsonx.NewObject()
	out.Set("ok", false)
	out.Set("error", errorObject)
	out.Set("name", name)
	text, marshalErr := jsonx.Marshal(out)
	if marshalErr != nil {
		return nil
	}
	encoded := string(text)
	return &encoded
}
