// Package golden runs the differential test corpus against the reference
// outputs produced by the original Rust implementation.
//
// The corpus (testdata/corpus.jsonl) and the reference results
// (testdata/goldens/rust.jsonl) are generated by tools/refgen, a small Rust
// binary built against the original crates. Every case is replayed through the
// Go implementation and the JSON output must match byte for byte, apart from
// volatile timestamps which are normalised to zero.
package golden

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"sync"
	"testing"

	"github.com/dandandujie/dsr-go/core/jsonx"
	"github.com/dandandujie/dsr-go/encoding"
	"github.com/dandandujie/dsr-go/encoding/tokenizer"
	"github.com/dandandujie/dsr-go/encoding/v4/dsv4"
	"github.com/dandandujie/dsr-go/encoding/v4/dsv41"
	"github.com/dandandujie/dsr-go/recipe/anthropic/messages"
	"github.com/dandandujie/dsr-go/recipe/openai/chatcompletion"
	"github.com/dandandujie/dsr-go/recipe/openai/responses"
	"github.com/dandandujie/dsr-go/recipe/request"
	"github.com/dandandujie/dsr-go/recipe/response"
	"github.com/dandandujie/dsr-go/recipe/stream"
)

// corpusCase is one differential test case.
type corpusCase struct {
	Name        string            `json:"name"`
	Op          string            `json:"op"`
	Protocol    string            `json:"protocol"`
	Body        json.RawMessage   `json:"body"`
	Chunks      []json.RawMessage `json:"chunks"`
	Tokenizer   string            `json:"tokenizer"`
	Value       json.RawMessage   `json:"value"`
	Text        string            `json:"text"`
	IDs         []uint32          `json:"ids"`
	Numbers     []string          `json:"numbers"`
	SkipSpecial bool              `json:"skip_special_tokens"`
	Encoding    string            `json:"encoding"`
}

// chunkSpec mirrors the refgen chunk specification.
type chunkSpec struct {
	Kind                 string  `json:"kind"`
	SystemFingerprint    *string `json:"system_fingerprint"`
	PromptTokens         int     `json:"prompt_tokens"`
	PromptCacheHitTokens int     `json:"prompt_cache_hit_tokens"`
	Content              string  `json:"content"`
	ContentTokens        int     `json:"content_tokens"`
	TokenID              uint32  `json:"token_id"`
	Text                 string  `json:"text"`
	FinishReason         string  `json:"finish_reason"`
}

// adapter binds one protocol package to the harness without generics.
type adapter struct {
	name string
	// convert deserializes and converts a request body.
	convert func(body []byte) (*request.ConversationRequest, error)
	// newGenerator builds the protocol event generator.
	newGenerator func(req *request.ConversationRequest, id, model string) stream.Generator
	// newResponse builds an empty accumulator for the protocol.
	newResponse func(id, model string, created uint64) response.ProtocolResponse
	// ops lists the operations that need this adapter.
	ops map[string]bool
}

func newChatCompletionsAdapter() *adapter {
	return &adapter{
		name: "chat_completions",
		convert: func(body []byte) (*request.ConversationRequest, error) {
			var typed chatcompletion.ChatCompletionRequest
			if err := json.Unmarshal(body, &typed); err != nil {
				return nil, request.BadRequestf("invalid request body: %v", err)
			}
			return typed.Convert(request.NewConversionOptions())
		},
		newGenerator: func(req *request.ConversationRequest, id, model string) stream.Generator {
			return req.NewChunkGenerator(id, model)
		},
		newResponse: func(id, model string, created uint64) response.ProtocolResponse {
			return chatcompletion.NewChatCompletionResponse(id, model, created)
		},
		ops: map[string]bool{"convert": true, "render": true, "encode": true, "stream": true, "complete": true},
	}
}

func newMessagesAdapter() *adapter {
	return &adapter{
		name: "messages",
		convert: func(body []byte) (*request.ConversationRequest, error) {
			var typed messages.MessagesRequest
			if err := json.Unmarshal(body, &typed); err != nil {
				return nil, request.BadRequestf("invalid request body: %v", err)
			}
			return typed.Convert(request.NewConversionOptions())
		},
		newGenerator: func(req *request.ConversationRequest, id, model string) stream.Generator {
			return req.NewChunkGenerator(id, model)
		},
		newResponse: func(id, model string, created uint64) response.ProtocolResponse {
			return messages.NewMessagesResponse(id, model, created)
		},
		ops: map[string]bool{"convert": true, "render": true, "encode": true, "stream": true, "complete": true},
	}
}

func newResponsesAdapter() *adapter {
	return &adapter{
		name: "responses",
		convert: func(body []byte) (*request.ConversationRequest, error) {
			var typed responses.ResponsesRequest
			if err := json.Unmarshal(body, &typed); err != nil {
				return nil, request.BadRequestf("invalid request body: %v", err)
			}
			return typed.Convert(request.NewConversionOptions())
		},
		newGenerator: func(req *request.ConversationRequest, id, model string) stream.Generator {
			return req.NewChunkGenerator(id, model)
		},
		newResponse: func(id, model string, created uint64) response.ProtocolResponse {
			return responses.NewResponsesResponse(id, model, created)
		},
		ops: map[string]bool{"convert": true, "render": true, "encode": true, "stream": true, "complete": true},
	}
}

func adapters() map[string]*adapter {
	list := []*adapter{newChatCompletionsAdapter(), newResponsesAdapter(), newMessagesAdapter()}
	out := make(map[string]*adapter, len(list))
	for _, item := range list {
		out[item.name] = item
	}
	return out
}

var (
	createdPattern = regexp.MustCompile(`"(created|created_at|completed_at)":\d+`)

	tokenizerMu    sync.Mutex
	tokenizerCache = map[string]*tokenizer.Tokenizer{}
)

func normalizeVolatile(text string) string {
	return createdPattern.ReplaceAllString(text, `"$1":0`)
}

// loadTokenizer loads a bundled tokenizer by directory name ("v4" or "v41").
func loadTokenizer(name string) (*tokenizer.Tokenizer, error) {
	if name == "" {
		name = "v41"
	}
	tokenizerMu.Lock()
	defer tokenizerMu.Unlock()
	if cached, ok := tokenizerCache[name]; ok {
		return cached, nil
	}
	path := filepath.Join("..", "static", "tokenizers", name, "tokenizer.json")
	loaded, err := tokenizer.Load(path)
	if err != nil {
		return nil, err
	}
	tokenizerCache[name] = loaded
	return loaded, nil
}

func loadCorpus(t *testing.T) ([]corpusCase, map[string]string) {
	t.Helper()
	root := filepath.Join("..", "testdata")
	corpusData, err := os.ReadFile(filepath.Join(root, "corpus.jsonl"))
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	goldenData, err := os.ReadFile(filepath.Join(root, "goldens", "rust.jsonl"))
	if err != nil {
		t.Fatalf("read goldens: %v", err)
	}
	var cases []corpusCase
	for _, line := range strings.Split(strings.TrimSpace(string(corpusData)), "\n") {
		if strings.TrimSpace(line) == "" {
			continue
		}
		var item corpusCase
		if err := json.Unmarshal([]byte(line), &item); err != nil {
			t.Fatalf("parse corpus line: %v", err)
		}
		cases = append(cases, item)
	}
	goldens := make(map[string]string)
	for _, line := range strings.Split(strings.TrimSpace(string(goldenData)), "\n") {
		if strings.TrimSpace(line) == "" {
			continue
		}
		var item struct {
			Name string `json:"name"`
		}
		if err := json.Unmarshal([]byte(line), &item); err != nil {
			t.Fatalf("parse golden line: %v", err)
		}
		goldens[item.Name] = line
	}
	return cases, goldens
}

func TestGoldenCorpus(t *testing.T) {
	cases, goldens := loadCorpus(t)
	registry := adapters()
	tested, skipped := 0, 0
	for _, item := range cases {
		item := item
		t.Run(item.Name, func(t *testing.T) {
			got, err := runCase(item, registry)
			if err != nil {
				t.Fatalf("run: %v", err)
			}
			if got == nil {
				skipped++
				t.Skip("operation not supported yet")
			}
			want, ok := goldens[item.Name]
			if !ok {
				t.Fatalf("no reference result for %s", item.Name)
			}
			tested++
			wantText := normalizeVolatile(want)
			gotText := normalizeVolatile(*got)
			if wantText != gotText {
				t.Errorf("reference mismatch\nwant: %s\n got: %s", wantText, gotText)
			}
		})
	}
	t.Logf("golden cases run: %d, skipped: %d", tested, skipped)
}

// runCase replays one corpus case and returns the JSON result, or nil when the
// operation is not implemented.
func runCase(item corpusCase, registry map[string]*adapter) (*string, error) {
	switch item.Op {
	case "stringify":
		value, err := jsonx.Parse(item.Value)
		if err != nil {
			return nil, err
		}
		text, err := jsonx.MarshalPython(value)
		if err != nil {
			return nil, err
		}
		result := jsonx.NewObject()
		result.Set("text", text)
		return encodeResult(item.Name, result), nil
	case "numbers":
		compact := make(jsonx.Array, 0, len(item.Numbers))
		python := make(jsonx.Array, 0, len(item.Numbers))
		for _, number := range item.Numbers {
			value, err := jsonx.ParseString(number)
			if err != nil {
				return nil, err
			}
			compactText, err := jsonx.Marshal(value)
			if err != nil {
				return nil, err
			}
			pythonText, err := jsonx.MarshalPython(value)
			if err != nil {
				return nil, err
			}
			compact = append(compact, string(compactText))
			python = append(python, pythonText)
		}
		result := jsonx.NewObject()
		result.Set("compact", compact)
		result.Set("python", python)
		return encodeResult(item.Name, result), nil
	case "tokenize":
		loaded, err := loadTokenizer(item.Tokenizer)
		if err != nil {
			return nil, err
		}
		ids, err := loaded.EncodeIDs(item.Text)
		if err != nil {
			return nil, err
		}
		array := make(jsonx.Array, 0, len(ids))
		for _, id := range ids {
			array = append(array, int64(id))
		}
		result := jsonx.NewObject()
		result.Set("ids", array)
		return encodeResult(item.Name, result), nil
	case "detokenize":
		loaded, err := loadTokenizer(item.Tokenizer)
		if err != nil {
			return nil, err
		}
		text, err := loaded.DecodeIDs(item.IDs, item.SkipSpecial)
		if err != nil {
			return nil, err
		}
		result := jsonx.NewObject()
		result.Set("text", text)
		return encodeResult(item.Name, result), nil
	}

	impl, ok := registry[item.Protocol]
	if !ok || !impl.ops[item.Op] {
		return nil, nil
	}
	converted, err := impl.convert(item.Body)
	if err != nil {
		return encodeError(item.Name, err), nil
	}
	switch item.Op {
	case "convert":
		return encodeResult(item.Name, dumpConversion(converted)), nil
	case "render":
		var rendered encoding.RenderedPrompt
		if item.Encoding == "v4" {
			rendered = dsv4.New().RenderConversation(converted.Conversation)
		} else {
			rendered = dsv41.New().RenderConversation(converted.Conversation)
		}
		result := jsonx.NewObject()
		result.Set("prompt", rendered.Prompt)
		result.Set("image_sources", dumpImages(rendered.ImageSources))
		return encodeResult(item.Name, result), nil
	case "encode":
		loaded, err := loadTokenizer(item.Tokenizer)
		if err != nil {
			return nil, err
		}
		var ids []uint32
		if item.Encoding == "v4" {
			ids, err = dsv4.New().WithTokenizer(loaded).Encode(converted.Conversation)
		} else {
			ids, err = dsv41.New().WithTokenizer(loaded).Encode(converted.Conversation)
		}
		if err != nil {
			return encodeError(item.Name, err), nil
		}
		array := make(jsonx.Array, 0, len(ids))
		for _, id := range ids {
			array = append(array, int64(id))
		}
		result := jsonx.NewObject()
		result.Set("ids", array)
		return encodeResult(item.Name, result), nil
	case "stream":
		return runStream(item, impl, converted)
	case "complete":
		return runComplete(item, impl, converted)
	}
	return nil, fmt.Errorf("unknown op %q", item.Op)
}

func runStream(item corpusCase, impl *adapter, converted *request.ConversationRequest) (*string, error) {
	specs, err := decodeChunks(item.Chunks)
	if err != nil {
		return nil, err
	}
	generator := impl.newGenerator(converted, "mock-id", "deepseek-flash")
	processor := stream.NewProcessor(generator, converted.ParsingOptions)
	inference, err := buildChunks(specs, item.Tokenizer)
	if err != nil {
		return nil, err
	}
	if needsTokenizer(specs) {
		loaded, err := loadTokenizer(item.Tokenizer)
		if err != nil {
			return nil, err
		}
		processor = processor.WithTokenizer(loaded)
	}
	events := make(jsonx.Array, 0, len(inference))
	for _, chunk := range inference {
		produced, err := processor.Push(chunk)
		if err != nil {
			return encodeError(item.Name, err), nil
		}
		for _, event := range produced {
			value, err := eventValue(event)
			if err != nil {
				return nil, err
			}
			events = append(events, value)
		}
	}
	for _, event := range processor.Finish() {
		value, err := eventValue(event)
		if err != nil {
			return nil, err
		}
		events = append(events, value)
	}
	result := jsonx.NewObject()
	result.Set("events", events)
	return encodeResult(item.Name, result), nil
}

func runComplete(item corpusCase, impl *adapter, converted *request.ConversationRequest) (*string, error) {
	specs, err := decodeChunks(item.Chunks)
	if err != nil {
		return nil, err
	}
	generator := impl.newGenerator(converted, "mock-id", "deepseek-flash")
	processor := stream.NewProcessor(generator, converted.ParsingOptions)
	inference, err := buildChunks(specs, item.Tokenizer)
	if err != nil {
		return nil, err
	}
	accumulator := impl.newResponse("mock-id", "deepseek-flash", 0)
	for _, chunk := range inference {
		produced, err := processor.Push(chunk)
		if err != nil {
			return encodeError(item.Name, err), nil
		}
		for _, event := range produced {
			accumulator.Append(event)
		}
	}
	for _, event := range processor.Finish() {
		accumulator.Append(event)
	}
	text, err := jsonx.MarshalCompactString(accumulator)
	if err != nil {
		return nil, err
	}
	value, err := jsonx.ParseString(text)
	if err != nil {
		return nil, err
	}
	return encodeResult(item.Name, value), nil
}

func needsTokenizer(specs []chunkSpec) bool {
	for _, spec := range specs {
		if spec.Kind == "token_text" {
			return true
		}
	}
	return false
}

func eventValue(event stream.Event) (jsonx.Value, error) {
	text, err := jsonx.MarshalCompactString(event)
	if err != nil {
		return nil, err
	}
	return jsonx.ParseString(text)
}

func decodeChunks(raw []json.RawMessage) ([]chunkSpec, error) {
	specs := make([]chunkSpec, 0, len(raw))
	for _, item := range raw {
		var spec chunkSpec
		if err := json.Unmarshal(item, &spec); err != nil {
			return nil, err
		}
		specs = append(specs, spec)
	}
	return specs, nil
}

func buildChunks(specs []chunkSpec, tokenizerName string) ([]stream.InferenceChunk, error) {
	chunks := make([]stream.InferenceChunk, 0, len(specs))
	for _, spec := range specs {
		switch spec.Kind {
		case "ready":
			chunks = append(chunks, stream.NewReadyChunk(spec.SystemFingerprint, stream.PromptUsage{
				PromptTokens:         spec.PromptTokens,
				PromptCacheHitTokens: spec.PromptCacheHitTokens,
			}))
		case "text":
			chunks = append(chunks, stream.NewTextChunk(spec.Content, spec.ContentTokens))
		case "token":
			chunks = append(chunks, stream.NewTokenChunk(spec.TokenID))
		case "token_text":
			loaded, err := loadTokenizer(tokenizerName)
			if err != nil {
				return nil, err
			}
			ids, err := loaded.EncodeIDs(spec.Text)
			if err != nil {
				return nil, err
			}
			for _, id := range ids {
				chunks = append(chunks, stream.NewTokenChunk(id))
			}
		case "finish":
			reason := stream.InferenceFinishStop
			switch spec.FinishReason {
			case "length":
				reason = stream.InferenceFinishLength
			case "content_filter":
				reason = stream.InferenceFinishContentFilter
			}
			chunks = append(chunks, stream.NewFinishChunk(reason))
		default:
			return nil, fmt.Errorf("unknown chunk kind %q", spec.Kind)
		}
	}
	return chunks, nil
}

func encodeResult(name string, result jsonx.Value) *string {
	out := jsonx.NewObject()
	out.Set("ok", true)
	out.Set("result", result)
	out.Set("name", name)
	text, err := jsonx.Marshal(out)
	if err != nil {
		return nil
	}
	encoded := string(text)
	return &encoded
}

func encodeError(name string, err error) *string {
	kind := "internal"
	detail := err.Error()
	if conversion, ok := err.(*request.ConversionError); ok {
		detail = conversion.Detail
		if conversion.Kind == request.ConversionBadRequest {
			kind = "bad_request"
		}
	}
	errorObject := jsonx.NewObject()
	errorObject.Set("kind", kind)
	errorObject.Set("detail", detail)
	out := jsonx.NewObject()
	out.Set("ok", false)
	out.Set("error", errorObject)
	out.Set("name", name)
	text, marshalErr := jsonx.Marshal(out)
	if marshalErr != nil {
		return nil
	}
	encoded := string(text)
	return &encoded
}
